name: Release

on:
  release:
    types: [published]

jobs:
  release_zip_file:
    name: Prepare release asset
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Get Version
        id: get_version
        run: echo ::set-output name=VERSION::${GITHUB_REF/refs\/tags\//}

      - name: "Set version numbmer"
        run: |
          sed -i '/VERSION = /c\VERSION = "${{ steps.get_version.outputs.VERSION }}"' ${{ github.workspace }}/custom_components/ha-renogy/const.py
          sed -i '/version/c\  \"version\": \"${{ steps.get_version.outputs.VERSION }}\",' ${{ github.workspace }}/custom_components/ha-renogy/manifest.json
      # Pack the ha-renogy dir as a zip and upload to the release
      - name: Create Zip File
        run: |
          cd ${{ github.workspace }}/custom_components/ha-renogy
          zip ha-renogy.zip -r ./
      - name: Upload zip to release
        uses: svenstaro/upload-release-action@v1-release
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: ${{ github.workspace }}/custom_components/ha-renogy/ha-renogy.zip
          asset_name: ha-renogy.zip
          tag: ${{ github.ref }}
          overwrite: true
