name: Release

on:
  workflow_dispatch:
  release:
    types: [published]

jobs:
  release_zip_file:
    name: Prepare release asset
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Get Version
        id: get_version
        #run: echo ::set-output name=VERSION::${GITHUB_REF/refs\/tags\//}
        run: echo "VERSION=${GITHUB_REF/refs\/tags\//}" >> $GITHUB_OUTPUT

      - name: "Set version numbmer"
        run: |
          sed -i '/VERSION = /c\VERSION = "${{ steps.get_version.outputs.VERSION }}"' ${{ github.workspace }}/custom_components/renogy/const.py
          sed -i '/version/c\  \"version\": \"${{ steps.get_version.outputs.VERSION }}\"' ${{ github.workspace }}/custom_components/renogy/manifest.json
      # Pack the ha-renogy dir as a zip and upload to the release
      - name: Create Zip File
        run: |
          cd ${{ github.workspace }}/custom_components/renogy
          zip renogy.zip -r ./
      - name: Upload zip to release
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: ${{ github.workspace }}/custom_components/renogy/renogy.zip
          asset_name: renogy.zip
          tag: ${{ github.ref }}
          overwrite: true
