name: Pull actions

on:
  pull_request:
  push:
    branches:
      - main

jobs:
  validate:
    runs-on: "ubuntu-latest"
    name: Validate
    steps:
        - name: 📥 Checkout the repository
          uses: actions/checkout@v4

        - name: HACS validation
          uses: "hacs/action@main"
          with:
            category: "integration"
            ignore: brands

        - name: Hassfest validation
          uses: "home-assistant/actions/hassfest@master"

  style:
    runs-on: "ubuntu-latest"
    name: Check style formatting
    steps:
        - name: 📥 Checkout the repository
          uses: actions/checkout@v4
        - name: 🛠️ Set up Python
          uses: actions/setup-python@v5
          with:
            python-version: "3.x"
        - name: 🏃 Run ruff
          run: |
            pip install ruff
            ruff check .
            ruff format --check .

  tests:
    runs-on: "ubuntu-latest"
    name: Run tests
    strategy:
      matrix:
        python-version:
          - "3.14"

    steps:
      - name: 📥 Checkout the repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 2
      - name: 🛠️ Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}
      - name: 📦 Install requirements
        run: |
          pip install tox tox-gh-actions
      - name: 🏃 Test with tox
        run: tox
      - name: 📤 Upload coverage to Codecov
        if: matrix.python-version == '3.14'
        uses: "actions/upload-artifact@v4"
        with:
          name: coverage-data
          path: "coverage.xml"

  coverage:
    runs-on: ubuntu-latest
    needs: tests
    steps:
      - name: 📥 Checkout the repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 2
      - name: 📥 Download coverage data
        uses: actions/download-artifact@v4
        with:
          name: coverage-data
      - name: 📤 Upload coverage report
        uses: codecov/codecov-action@v4
        with:
          token: ${{ secrets.CODECOV_TOKEN }} # required
